--Magnitude - Comapring the measure values by categories

--Find total customers by country
select
country,
count(customer_id) as total_customers
from 
gold.dim_customers
group by country
order by count(customer_id) DESC

--find total customers by gender
select
gender,
count(customer_id) as total_customers
from 
gold.dim_customers
group by gender
order by count(customer_id) DESC

--find total products by category
select
category,
count(product_name) total_products
from gold.dim_products
group by category
order by category DESC

--What is the average costs in each category
select 
category,
avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg(cost) desc

--what is the total revenue generated in each category
select p.category, SUM(s.sales_amount) total_revenue
from gold.dim_products p
INNER JOIN gold.fact_sales s
on p.product_key = s.product_key
group by p.category
order by SUM(s.sales_amount) desc

--Total revenue generated by each customer
select p.customer_key,
p.first_name,
p.last_name,
SUM(s.sales_amount) total_revenue
from gold.dim_customers p
INNER JOIN gold.fact_sales s
on p.customer_key = s.customer_key
group by p.customer_key, first_name,
p.last_name
order by SUM(s.sales_amount) desc


